---
name: 'deploy review app'

on:
  pull_request

jobs:
  create_review_app:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create review app
        uses: appleboy/ssh-action@master
        with:
          host: 15.237.10.169
          username: dokku
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./deploy_branch.sh ${{ github.event.pull_request.number }}

      - name: Deploy PR to review app
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 15.237.10.169
          app-name: klaradev-${{ github.event.pull_request.number }}
          remote-branch: ${{ github.head_ref }}

      - name: Populate database for new review app
        uses: appleboy/ssh-action@master
        with:
          host: 15.237.10.169
          username: dokku
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            dokku run klaradev-${{ github.event.pull_request.number }} rails db:seed
          
  synchronize_review_app:
    runs-on: ubuntu-latest
    if: github.event.action == 'synchronize'
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update application with new changes
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: 15.237.10.169
          app-name: klaradev-${{ github.event.pull_request.number }}
          remote-branch: ${{ github.head_ref }}
          
  destroy_review_app:
    runs-on: ubuntu-latest
    # only run when a pull request is closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    steps:
      - name: Destroy review app
        uses: appleboy/ssh-action@master
        with:
          host: 15.237.10.169
          username: dokku
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ./remove_branch.sh ${{ github.event.pull_request.number }}